/**
 * AI Query Generator
 * 
 * Converts natural language questions to structured MongoDB queries.
 * 
 * Security principles:
 * - NEVER execute generated queries directly
 * - Always generate only structured query objects
 * - Only support read operations (find, count)
 * - Only use fields defined in databaseSchema.js
 * - Never use dynamic/dangerous MongoDB operators
 * - Provider is configurable (not hardcoded)
 * - Generated queries MUST pass through queryValidator.js
 * 
 * Architecture:
 * Natural Language → aiQueryGenerator → Structured Query → queryValidator → queryExecutor
 */

import databaseSchema from '../config/databaseSchema.js';

/**
 * Generate a structured query from a natural language question
 * 
 * This function is the main entry point. It:
 * 1. Validates input
 * 2. Calls the configured AI provider (optionally with discovered schema for context)
 * 3. Sanitizes the AI output
 * 4. Returns a structured query object (or null on failure)
 * 
 * CRITICAL: Does NOT execute the query. That's queryExecutor's job.
 * CRITICAL: Validator must run on the output. Never skip validation.
 * 
 * @param {string} normalizedQuestion - The normalized natural language question
 * @param {Object|undefined} discoveredSchema - Optional discovered MongoDB schema for AI context
 * @returns {Promise<Object|null>} - Structured query object or null
 */
export const generateQuery = async (normalizedQuestion, discoveredSchema) => {
  // Step 1: Validate input
  if (typeof normalizedQuestion !== 'string' || normalizedQuestion.trim().length === 0) {
    console.error('AI: Invalid normalized question input');
    return null;
  }

  try {
    // Step 2: Get the configured provider
    const provider = getAIProvider();

    if (!provider) {
      console.error('AI: No AI provider configured');
      return null;
    }

    // Step 3: Generate query using the provider (optionally with discovered schema)
    const generatedQuery = await provider.generateQuery(normalizedQuestion, discoveredSchema);

    if (!generatedQuery) {
      console.error('AI: Provider returned null/undefined');
      return null;
    }

    // Step 4: Sanitize the generated query (ensure it's a safe object)
    const sanitizedQuery = sanitizeGeneratedQuery(generatedQuery);

    if (!sanitizedQuery) {
      console.error('AI: Generated query failed sanitization');
      return null;
    }

    // Step 5: Return the sanitized query
    // NOTE: This query MUST be validated by queryValidator.js before execution
    // NOTE: Discovered schema is informational only; validation uses hardcoded databaseSchema.js
    return sanitizedQuery;
  } catch (error) {
    console.error('AI generation error:', error.message);
    return null;
  }
};

/**
 * Sanitize a query object generated by AI
 * 
 * This is a defensive measure against:
 * - Malformed objects
 * - Prototype pollution
 * - Unexpected properties
 * - Functions or circular references
 * 
 * @param {*} query - The generated query
 * @returns {Object|null} - Sanitized query or null if invalid
 */
function sanitizeGeneratedQuery(query) {
  // Must be a plain object
  if (!isPlainObject(query)) {
    return null;
  }

  // Create a new object with only expected top-level properties
  const sanitized = {
    ...(query.collectionName && { collectionName: String(query.collectionName) }),
    ...(query.operation && { operation: String(query.operation) }),
    ...(query.filter && typeof query.filter === 'object' && { filter: sanitizeFilterObject(query.filter) }),
    ...(query.projection && typeof query.projection === 'object' && { projection: sanitizeFilterObject(query.projection) }),
    ...(query.sort && typeof query.sort === 'object' && { sort: sanitizeFilterObject(query.sort) }),
    ...(query.limit !== undefined && typeof query.limit === 'number' && { limit: query.limit }),
    ...(query.skip !== undefined && typeof query.skip === 'number' && { skip: query.skip }),
  };

  // Must have at least collectionName and operation
  if (!sanitized.collectionName || !sanitized.operation) {
    return null;
  }

  return sanitized;
}

/**
 * Sanitize a filter/projection/sort object
 * Recursively sanitizes nested objects to prevent prototype pollution
 * 
 * @param {*} obj - The object to sanitize
 * @param {number} depth - Current recursion depth (prevent infinite recursion)
 * @returns {Object} - Sanitized object
 */
function sanitizeFilterObject(obj, depth = 0) {
  // Prevent infinite recursion
  if (depth > 10) {
    return {};
  }

  if (!isPlainObject(obj)) {
    return {};
  }

  const sanitized = {};

  for (const [key, value] of Object.entries(obj)) {
    // Skip dangerous keys
    if (key.startsWith('__') || key === 'constructor' || key === 'prototype') {
      continue;
    }

    // Recursively sanitize nested objects
    if (isPlainObject(value)) {
      sanitized[key] = sanitizeFilterObject(value, depth + 1);
    } else if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean' || value === null) {
      sanitized[key] = value;
    } else if (Array.isArray(value)) {
      // Only allow simple arrays of primitives
      sanitized[key] = value.filter(
        (item) => typeof item === 'string' || typeof item === 'number' || typeof item === 'boolean' || item === null
      );
    }
    // Silently drop other types (functions, dates, etc.)
  }

  return sanitized;
}

/**
 * Check if value is a plain object (not array, function, class, etc.)
 */
function isPlainObject(obj) {
  if (obj === null || obj === undefined) return false;
  if (typeof obj !== 'object') return false;
  if (Array.isArray(obj)) return false;
  if (obj instanceof Date) return false;
  if (obj instanceof RegExp) return false;
  if (obj instanceof Function) return false;
  if (obj.constructor !== Object) return false;
  return true;
}

/**
 * Get the configured AI provider
 * 
 * This function handles provider selection based on environment variables.
 * Currently supports:
 * - OpenAI (configured via OPENAI_API_KEY)
 * - Mock provider (for testing, when NO_AI=true)
 * 
 * Extend this function to add new providers.
 * 
 * @returns {Object|null} - Provider with generateQuery(question) method
 */
function getAIProvider() {
  // Check if testing mode is enabled (mock provider)
  if (process.env.NO_AI === 'true') {
    return getMockProvider();
  }

  // Check if OpenAI is configured
  const openaiApiKey = process.env.OPENAI_API_KEY;
  if (openaiApiKey) {
    return getOpenAIProvider(openaiApiKey);
  }

  // No provider configured
  console.warn('AI: No provider configured. Set OPENAI_API_KEY or NO_AI=true for testing.');
  return null;
}

/**
 * Get the OpenAI provider
 * 
 * Uses OpenAI's API to generate queries.
 * Requires OPENAI_API_KEY environment variable.
 * 
 * @param {string} apiKey - OpenAI API key
 * @returns {Object} - Provider object with generateQuery method
 */
function getOpenAIProvider(apiKey) {
  // We'll dynamically import openai package only if needed
  // This is intentional - we don't want to force the dependency
  return {
    async generateQuery(question, discoveredSchema) {
      try {
        // Lazy import to avoid hard dependency
        const { OpenAI } = await import('openai');

        const client = new OpenAI({
          apiKey: apiKey,
        });

        const allowedCollections = Object.keys(databaseSchema.collections).filter(
          (name) => databaseSchema.isCollectionAllowed(name)
        );

        const collectionsInfo = allowedCollections
          .map((colName) => {
            const colSchema = databaseSchema.collections[colName];
            const fields = Object.entries(colSchema.fields)
              .filter(([key, config]) => key !== '_id' && config.filterable)
              .map(([key, config]) => `${key} (${config.type})`)
              .join(', ');
            return `- ${colName}: ${fields}`;
          })
          .join('\n');

        const systemPrompt = `You are a MongoDB query generator. Convert natural language questions to structured MongoDB queries.

IMPORTANT RULES:
1. You MUST respond with ONLY valid JSON, no explanation or markdown
2. The JSON must be a single structured query object
3. Allowed collections and their fields:
${collectionsInfo}
4. ONLY use operations: find, count
5. For CGPA comparisons, use: { "cgpa": { "$gt": value } }
6. For branch matching, use exact strings like "Computer Science"
7. Always set "collectionName" to either "students" or "courses"
8. Always include "operation" (find or count)
9. Never invent fields not listed above
10. Never use write operations (insert, update, delete)

Examples:
Q: "Show all students" → {"collectionName":"students","operation":"find","filter":{}}
Q: "Show CS students" → {"collectionName":"students","operation":"find","filter":{"branch":"Computer Science"}}
Q: "Students with CGPA > 8.5" → {"collectionName":"students","operation":"find","filter":{"cgpa":{"$gt":8.5}}}
Q: "Count CS students" → {"collectionName":"students","operation":"count","filter":{"branch":"Computer Science"}}
Q: "Show all courses" → {"collectionName":"courses","operation":"find","filter":{}}
Q: "Show courses with 4 credits" → {"collectionName":"courses","operation":"find","filter":{"credits":4}}
Q: "Who teaches Database Systems?" → {"collectionName":"courses","operation":"find","filter":{"title":"Database Systems"}}
Q: "How many courses?" → {"collectionName":"courses","operation":"count","filter":{}}
Q: "Count courses" → {"collectionName":"courses","operation":"count","filter":{}}`;

        const response = await client.chat.completions.create({
          model: 'gpt-3.5-turbo',
          messages: [
            {
              role: 'system',
              content: systemPrompt,
            },
            {
              role: 'user',
              content: `Convert this question to a query: "${question}"`,
            },
          ],
          temperature: 0,
          max_tokens: 300,
        });

        const content = response.choices[0]?.message?.content || '';

        // Try to parse the response as JSON
        try {
          // Remove markdown code blocks if present
          const jsonStr = content
            .replace(/^```json\n?/, '')
            .replace(/\n?```$/, '')
            .trim();

          const parsed = JSON.parse(jsonStr);
          return parsed;
        } catch (parseError) {
          console.error('AI: Failed to parse OpenAI response as JSON:', content);
          return null;
        }
      } catch (error) {
        console.error('AI: OpenAI provider error:', error.message);
        return null;
      }
    },
  };
}

/**
 * Get the mock provider for testing
 * 
 * Returns hardcoded responses for common questions.
 * Useful for testing without API credentials or costs.
 * 
 * @returns {Object} - Provider object with generateQuery method
 */
function getMockProvider() {
  return {
    async generateQuery(question, discoveredSchema) {
      // discoveredSchema is available for context but not required
      // The mock provider continues to use hardcoded logic
      // Simple pattern matching for common questions
      const q = question.toLowerCase();

      // Count queries (check BEFORE show queries)
      if (q.includes('count') || q.includes('how many')) {
        if (q.includes('course')) {
          return {
            collectionName: 'courses',
            operation: 'count',
            filter: {},
          };
        }
        if (
          q.includes('computer science') ||
          q.includes('cs') ||
          (q.includes('cse') && q.includes('student'))
        ) {
          return {
            collectionName: 'students',
            operation: 'count',
            filter: {
              branch: 'Computer Science',
            },
          };
        }
        return {
          collectionName: 'students',
          operation: 'count',
          filter: {},
        };
      }

      // Top students by CGPA (check before general show)
      if (q.includes('top') && q.includes('cgpa')) {
        const limitMatch = q.match(/top\s+(\d+)/i);
        return {
          collectionName: 'students',
          operation: 'find',
          filter: {},
          sort: {
            cgpa: -1,
          },
          limit: limitMatch ? parseInt(limitMatch[1]) : 5,
        };
      }

      // Course: Who teaches / instructor queries
      if (q.includes('teaches') || q.includes('instructor')) {
        if (q.includes('database systems')) {
          return {
            collectionName: 'courses',
            operation: 'find',
            filter: {
              title: 'Database Systems',
            },
          };
        }
        const teachesMatch = question.match(/(?:who\s+teaches|instructor\s+(?:for|of))\s+([^?]+)/i);
        if (teachesMatch && teachesMatch[1].trim()) {
          return {
            collectionName: 'courses',
            operation: 'find',
            filter: {
              title: teachesMatch[1].trim(),
            },
          };
        }
      }

      // Course: credits filtering
      if (q.includes('credit')) {
        const creditsMatch = q.match(/(\d+)\s+credits?/i) || q.match(/credits?\s+(?:with|of|=|:)?\s*(\d+)/i);
        if (creditsMatch) {
          return {
            collectionName: 'courses',
            operation: 'find',
            filter: {
              credits: parseInt(creditsMatch[1], 10),
            },
          };
        }
      }

      // Course: Show all courses
      if (q.includes('course') && (q.includes('show') || q.includes('all') || q.includes('list'))) {
        return {
          collectionName: 'courses',
          operation: 'find',
          filter: {},
        };
      }

      // Show all students
      if (q.includes('all') && q.includes('student') && !q.includes('computer science') && !q.includes('cgpa')) {
        return {
          collectionName: 'students',
          operation: 'find',
          filter: {},
        };
      }

      // CS students
      if (
        q.includes('computer science') ||
        q.includes('cs') ||
        (q.includes('cse') && q.includes('student'))
      ) {
        return {
          collectionName: 'students',
          operation: 'find',
          filter: {
            branch: 'Computer Science',
          },
        };
      }

      // CGPA comparisons
      if (q.includes('cgpa')) {
        const cgpaMatch = q.match(/cgpa\s+(?:above|over|>|greater|more)\s+([\d.]+)/i);
        if (cgpaMatch) {
          return {
            collectionName: 'students',
            operation: 'find',
            filter: {
              cgpa: {
                $gt: parseFloat(cgpaMatch[1]),
              },
            },
          };
        }
      }

      // Year filtering
      if (q.includes('year')) {
        const yearMatch = q.match(/year\s+(\d)/i);
        if (yearMatch) {
          return {
            collectionName: 'students',
            operation: 'find',
            filter: {
              year: parseInt(yearMatch[1]),
            },
          };
        }
      }

      // General "show students" without specific filters
      if (q.includes('student') && q.includes('show')) {
        return {
          collectionName: 'students',
          operation: 'find',
          filter: {},
        };
      }

      // Unrecognized question - return null (not a failure, just no match)
      return null;
    },
  };
}

export default generateQuery;
